// This file is auto-generated by TanStack Router

import { createFileRoute } from "@tanstack/react-router";

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as AuthLayoutImport } from "./routes/_authLayout";

// Create Virtual Routes

const BasicLayoutLazyImport = createFileRoute("/_basicLayout")();
const IndexLazyImport = createFileRoute("/")();
const BasicLayoutAppLazyImport = createFileRoute("/_basicLayout/app")();
const AuthLayoutLoginLazyImport = createFileRoute("/_authLayout/login")();

// Create/Update Routes

const BasicLayoutLazyRoute = BasicLayoutLazyImport.update({
  id: "/_basicLayout",
  getParentRoute: () => rootRoute,
} as any).lazy(() => import("./routes/_basicLayout.lazy").then((d) => d.Route));

const AuthLayoutRoute = AuthLayoutImport.update({
  id: "/_authLayout",
  getParentRoute: () => rootRoute,
} as any);

const IndexLazyRoute = IndexLazyImport.update({
  path: "/",
  getParentRoute: () => rootRoute,
} as any).lazy(() => import("./routes/index.lazy").then((d) => d.Route));

const BasicLayoutAppLazyRoute = BasicLayoutAppLazyImport.update({
  path: "/app",
  getParentRoute: () => BasicLayoutLazyRoute,
} as any).lazy(() => import("./routes/_basicLayout/app.lazy").then((d) => d.Route));

const AuthLayoutLoginLazyRoute = AuthLayoutLoginLazyImport.update({
  path: "/login",
  getParentRoute: () => AuthLayoutRoute,
} as any).lazy(() => import("./routes/_authLayout/login.lazy").then((d) => d.Route));

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      preLoaderRoute: typeof IndexLazyImport;
      parentRoute: typeof rootRoute;
    };
    "/_authLayout": {
      preLoaderRoute: typeof AuthLayoutImport;
      parentRoute: typeof rootRoute;
    };
    "/_basicLayout": {
      preLoaderRoute: typeof BasicLayoutLazyImport;
      parentRoute: typeof rootRoute;
    };
    "/_authLayout/login": {
      preLoaderRoute: typeof AuthLayoutLoginLazyImport;
      parentRoute: typeof AuthLayoutImport;
    };
    "/_basicLayout/app": {
      preLoaderRoute: typeof BasicLayoutAppLazyImport;
      parentRoute: typeof BasicLayoutLazyImport;
    };
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  AuthLayoutRoute.addChildren([AuthLayoutLoginLazyRoute]),
  BasicLayoutLazyRoute.addChildren([BasicLayoutAppLazyRoute]),
]);
